name: distributed-chat-system-dev

services:
  frontend:
    build:
      context: ./Frontend
      dockerfile: frontend.Dockerfile
    ports:
      - $FRONTEND_PORT:5173
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    container_name: distributed-chat-system-frontend
    env_file:
      - $FRONTEND_ENV

  db-service:
    build:
      context: ./Backend/db-service
      dockerfile: Dockerfile
    ports:
      - $DB_SERVICE_PORT:$DB_SERVICE_PORT
    volumes:
      - ./Backend/db-service:/app
      - ./Backend/services:/services
      - /app/node_modules
    container_name: distributed-chat-system-backend-db-service
    env_file:
      - $DB_SERVICE_ENV
    depends_on:
      - psql-write
      - psql-read

  api-gateway:
    build:
      context: ./Backend/api-gateway
      dockerfile: Dockerfile
    ports:
      - $API_SERVER_PORT:$API_SERVER_PORT
    volumes:
      - ./Backend/api-gateway:/app
      - ./Backend/services:/services
      - /app/node_modules
    container_name: distributed-chat-system-backend-api-gateway
    env_file:
      - $API_GATEWAY_ENV

  auth-service:
    build:
      context: ./Backend/auth-service
      dockerfile: Dockerfile
    ports:
      - $AUTH_SERVICE_PORT:$AUTH_SERVICE_PORT
    volumes:
      - ./Backend/auth-service:/app
      - ./Backend/services:/services
      - /app/node_modules
    container_name: distributed-chat-system-backend-auth-service
    env_file:
      - $AUTH_SERVICE_ENV

  ws-gateway-1:
    build:
      context: ./Backend/ws-gateway
      dockerfile: Dockerfile
    expose:
      - $WS_GATEWAY_PORT
    volumes:
      - ./Backend/ws-gateway:/app
      - ./Backend/services:/services
      - /app/node_modules
    container_name: distributed-chat-system-backend-ws-gateway-1
    env_file:
      - $WS_GATEWAY_ENV

  ws-gateway-2:
    build:
      context: ./Backend/ws-gateway
      dockerfile: Dockerfile
    expose:
      - $WS_GATEWAY_PORT
    volumes:
      - ./Backend/ws-gateway:/app
      - ./Backend/services:/services
      - /app/node_modules
    container_name: distributed-chat-system-backend-ws-gateway-2
    env_file:
      - $WS_GATEWAY_ENV

  nginx-ws-load-balancer:
    image: nginx:alpine
    container_name: distributed-chat-system-nginx-ws
    volumes:
      - ./Backend/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "$WS_GATEWAY_PORT:80"
    depends_on:
      - ws-gateway-1
      - ws-gateway-2

  redis-cache:
    image: redis:8.2-alpine
    container_name: distributed-chat-system-redis-cache
    expose:
      - 6379

  redis-pub-sub:
    image: redis:8.2-alpine
    container_name: distributed-chat-system-redis-pub-sub
    expose:
      - 6379

  psql-write:
    image: postgres:15-alpine
    container_name: distributed-chat-system-psql-write
    restart: unless-stopped
    expose:
      - 5432
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    command: >
      postgres -c wal_level=replica
               -c max_wal_senders=10
               -c max_replication_slots=10
               -c listen_addresses='*'
    volumes:
      - pgDataW:/var/lib/postgresql/data
      - ./init-repl.sh:/docker-entrypoint-initdb.d/init-repl.sh:ro

  psql-read:
    image: postgres:15-alpine
    restart: unless-stopped
    expose:
      - 5432
    environment:
      PGPASSWORD: replpass
    command: >
      bash -c "
        sleep 15 &&
        rm -rf /var/lib/postgresql/data/* &&
        su-exec postgres pg_basebackup -h psql-write -U repl -D /var/lib/postgresql/data -Fp -Xs -P -R &&
        chown -R postgres:postgres /var/lib/postgresql/data &&
        chmod 700 /var/lib/postgresql/data &&
        exec su-exec postgres postgres
      "
    volumes:
      - pgDataR:/var/lib/postgresql/data
    depends_on:
      - psql-write

volumes:
  pgDataW:
  pgDataR: